# Generated by Django 5.0.7 on 2024-08-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolink',
            name='photo_link',
            field=models.CharField(max_length=2000),
        ),
    ]
