# Generated by Django 5.0.7 on 2024-08-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_photolink_photo_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photolink',
            name='is_related_to_city',
        ),
    ]
